Repository creativecommons/cccatalog-frontend, pull requests merged in 2020-09, with the labels that each got.

#1219 Add Donation Banner to top of CC Search
  package-lock.json
  package.json
  src/components/DonationBanner.vue
  src/components/HeaderSection.vue
  src/locales/en.json
Labels: feature, 🌟 goal: addition

#1222 Fix support page donate links; Tweak banner spacing
  src/components/HeaderSection.vue
  src/pages/SupportPage.vue
Labels: 🛠 goal: fix, 🟥 priority: critical

#1228 Fixes search icon alignment
  src/components/SearchGridForm.vue
Labels: 🕹 aspect: interface, 🛠 goal: fix
