Repository creativecommons/cccatalog-frontend, pull requests merged in 2020-08, with the labels that each got.

#1107 Sentry Error Reporting Improvements
  .github/workflows/sentry-release.yml
  config/.env
  package-lock.json
  package.json
  server.js
  src/clientEntry.js
  src/sentry/browser.js
  src/sentry/initSentry.js
  src/sentry/server.js
  src/serverEntry.js
  test/unit/specs/sentry/init-sentry.spec.js
Labels: internal improvement

#1109 Swallow duplicate nav errors
  src/router/redirectTo.js
  test/unit/specs/router/redirectTo.spec.js
Labels: bug

#1111 Fix faulty conditional that prevented source logos from loading
  src/components/CollectionItem.vue
Labels: bug

#1112 Make sure global header renders once; Remove max-width restriction on global header tab
  src/App.vue
Labels: bug

#1119 Source and Provider name fallback
  package-lock.json
  package.json
  src/utils/getProviderName.js
Labels: bug

#1120 internationalize aria-labels for about page and feedback page
  src/locales/en.json
  src/locales/fr.json
  src/pages/AboutPage.vue
  src/pages/FeedbackPage.vue
Labels: accessibility (a11y)

#1123 Aria labels and internationalization
  package.json
  src/components/AppModal.vue
  src/components/BugReport.vue
  src/components/ContentReport/ContentReportForm.vue
  src/components/ContentReport/DmcaNotice.vue
  src/components/Filters/FilterBlock.vue
  src/components/Filters/FilterChecklist.vue
  src/components/Filters/FiltersList.vue
  src/components/Filters/LicenseExplanationTooltip.vue
  src/components/ImageDetails/ImageAttribution.vue
  src/components/ImageDetails/ImageInfo.vue
  src/components/ImageDetails/PhotoDetails.vue
  src/components/ImageDetails/SocialShareButtons.vue
  src/components/MetaSearch/MetaSearchCard.vue
  src/components/MetaSearch/MetaSearchForm.vue
  src/components/MetaSearch/MetaSourceList.vue
  src/components/ScrollButton.vue
  src/components/SearchGridForm.vue
  src/components/SearchGridManualLoad.vue
  src/components/SearchRating.vue
  src/locales/en.json
  src/locales/fr.json
  src/pages/PhotoDetailPage.vue
  test/unit/specs/components/ImageDetails/social-share-buttons.spec.js
  test/unit/specs/components/bug-report.spec.js
  test/unit/specs/components/scroll-button.spec.js
  test/unit/specs/pages/photodetailpage.spec.js
Labels: accessibility (a11y), internationalization (i18n)

#1121 setup vue-a11y for eslint
  .eslintrc.js
  package-lock.json
  package.json
  src/components/AppModal.vue
  src/components/ContentReport/ContentReportForm.vue
  src/components/ContentReport/DmcaNotice.vue
  src/components/ContentReport/OtherIssueForm.vue
  src/components/ContentReport/ReportError.vue
  src/components/Filters/FilterBlock.vue
  src/components/Filters/FilterChecklist.vue
  src/components/Filters/FiltersList.vue
  src/components/ImageDetails/CopyLicense.vue
  src/components/ImageDetails/PhotoDetails.vue
  src/components/ImageDetails/ReuseSurvey.vue
  src/components/ImageDetails/SocialShareButtons.vue
  src/components/LocaleSelector.vue
  src/components/MetaSearch/MetaSearchCard.vue
  src/components/NavSection.vue
  src/components/PhotoTags.vue
  src/components/SafeBrowsing.vue
  src/components/ScrollButton.vue
  src/components/SearchGridForm.vue
  src/components/SearchGridManualLoad.vue
  src/components/SearchRating.vue
  src/components/Tooltip.vue
  src/pages/FeedbackPage.vue
Labels: accessibility (a11y)

#1129 Update vocabulary + bulma, Add subtitle
  package-lock.json
  package.json
  src/components/HeroSection.vue
  src/locales/en.json
  src/locales/fr.json
Labels: bug

#1139 Feature/fix visual regressions
  src/App.vue
  src/components/ImageDetails/CopyLicense.vue
Labels: bug

#1146 Store filter sidebar toggle state in localstorage
  src/store/filter-store.js
  src/utils/local.js
Labels: enhancement

#1122 Add End to End Testing with Cypress
  .eslintrc.js
  .github/workflows/end-to-end-tests.yml
  .gitignore
  cypress.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/components/ImageDetails/PhotoDetails.vue
  test/e2e/search.spec.js
Labels: internal improvement

#1150 Fix redirection after filter change
  src/store/filter-store.js
  test/unit/specs/store/filter-store.spec.js
Labels: bug

#1158 Fix codeowners files
  .github/CODEOWNERS
  .prettierignore
  CODEOWNERS
  package.json
Labels: internal improvement

#1175 Fix meta search query update issues
  src/components/SearchGridForm.vue
  src/store/search-store.js
  test/unit/specs/store/search-store.spec.js
Labels: bug
