Repository creativecommons/cccatalog-frontend, pull requests merged in 2020-07, with the labels that each got.

#978 Fix incorrect bottom-padding spacing in content section
  src/components/ImageDetails/PhotoDetails.vue
Labels: question

#1003 Refactor search store
  CODEBASE.md
  src/pages/PhotoDetailPage.vue
  src/pages/client/PhotoDetailPage.vue
  src/pages/server/PhotoDetailPage.vue
  src/router/client.js
  src/router/server.js
  src/store/index.js
  src/store/related-images-store.js
  src/store/search-store.js
  test/unit/specs/pages/client/photodetailpage.spec.js
  test/unit/specs/pages/photodetailpage.spec.js
  test/unit/specs/store/related-images-store.spec.js
  test/unit/specs/store/search-store.spec.js
Labels: Great Contribution, enhancement

#1068 Accessibility
  src/components/HeroSection.vue
  src/components/NavSection.vue
  src/pages/AboutPage.vue
  src/pages/SearchHelpPage.vue
Labels: accessibility (a11y)

#1072 Accessibility Improvements
  src/components/ContentReport/ContentReportForm.vue
  src/components/ContentReport/DmcaNotice.vue
  src/components/ContentReport/DoneMessage.vue
  src/components/Filters/FilterBlock.vue
  src/components/Filters/FilterChecklist.vue
  src/components/Filters/FiltersList.vue
  src/components/Filters/SearchGridFilter.vue
  src/components/ImageDetails/CopyLicense.vue
  src/components/ImageDetails/ImageAttribution.vue
  src/components/ImageDetails/ImageInfo.vue
  src/components/ImageDetails/PhotoDetails.vue
  src/components/ImageDetails/SocialShareButtons.vue
  src/components/ScrollButton.vue
  src/components/SearchGridCell.vue
  src/components/SearchGridForm.vue
  src/components/SearchGridManualLoad.vue
  src/components/SearchRating.vue
  src/components/SearchTypeTabs.vue
  src/pages/BrowsePage.vue
  src/pages/CollectionsPage.vue
  src/pages/FeedbackPage.vue
  src/pages/PhotoDetailPage.vue
Labels: accessibility (a11y)

#1083 Add label for use filters
  src/components/AppModal.vue
  src/components/MetaSearch/MetaSearchForm.vue
  src/components/MetaSearch/MetaSearchModal.vue
Labels: Release blocker

#1085 Fix img width/height detection
  src/components/SearchGridCell.vue
Labels: bug

#1094 Add Nappy.co to meta image search
  src/components/MetaSearch/MetaSearchCard.vue
  src/utils/getLegacySourceUrl.js
Labels: enhancement

#1090 Remove `/collection/{name}` routes and refactor Browse page
  package-lock.json
  src/components/CollectionItem.vue
  src/components/Filters/FilterDisplay.vue
  src/components/Filters/FiltersList.vue
  src/components/Filters/SearchGridFilter.vue
  src/pages/BrowsePage.vue
  src/pages/CollectionBrowsePage.vue
  src/pages/HomePage.vue
  src/pages/PhotoDetailPage.vue
  src/router/index.js
  src/router/redirectOnEmptySearch.js
  src/store/filter-store.js
  src/store/mutation-types.js
  src/store/search-store.js
  src/utils/searchQueryTransform.js
  test/unit/specs/components/search-grid-filter.spec.js
  test/unit/specs/pages/collectionbrowsepage.spec.js
  test/unit/specs/pages/homepage.spec.js
  test/unit/specs/store/filter-store.spec.js
Labels: enhancement

#1098 Add CC Global Header
  src/App.vue
Labels: feature
