Repository creativecommons/cccatalog-frontend, pull requests merged in 2020-10, with the labels that each got.

#1238 Register Creator and Image source clicks with Analitics API
  src/components/ImageDetails/CopyLicense.vue
  src/components/ImageDetails/ImageInfo.vue
  src/components/ImageDetails/PhotoDetails.vue
Labels: internal improvement, 💻 aspect: code, 🛠 goal: fix

#1244 Fix A/B test initialization
  nuxt.config.js
  package-lock.json
  package.json
  src/abTests/experiments/donationLanguage.js
  src/abTests/experiments/filterExpansion.js
  src/abTests/index.js
  src/abTests/lib/createSixpackSession.js
  src/components/DonationBanner.vue
  src/components/HeaderSection.vue
  src/plugins/ab-test-init.js
  src/store-modules/abtest-store.js
  src/utils/sixpack.js
  test/unit/specs/ab-tests.spec.js
  test/unit/specs/abTests/experiment.spec.js
Labels: 🛠 goal: fix, 🟥 priority: critical

#1245 Release v2020.10.2
  .eslintrc.js
  nuxt.config.js
  package-lock.json
  package.json
  src/abTests/experiments/donationLanguage.js
  src/abTests/experiments/filterExpansion.js
  src/abTests/index.js
  src/abTests/lib/createSixpackSession.js
  src/components/AppModal.vue
  src/components/DonationBanner.vue
  src/components/Filters/FilterBlock.vue
  src/components/Filters/FiltersList.vue
  src/components/HeaderSection.vue
  src/components/HeroSection.vue
  src/components/SearchGridForm.vue
  src/components/SearchGridManualLoad.vue
  src/layouts/default.vue
  src/layouts/with-nav-search.vue
  src/pages/about.vue
  src/pages/photos/_id.vue
  src/pages/search.vue
  src/pages/sources.vue
  src/plugins/ab-test-init.js
  src/store-modules/abtest-store.js
  src/utils/sixpack.js
  test/unit/specs/ab-tests.spec.js
  test/unit/specs/abTests/experiment.spec.js
Labels: dependencies
